### ISSUE TITLE
Network view

### ISSUE THREAD

**Issue by amtinits** [chairmanmeow50/Brainspawn#15]
- Create a 2D projection of the network's nodes
- Decide what to do for large networks
- Decide what to do for networks where position is important but 2D projection would be cluttered

---
- Look at original Java code to see if it's using a layout library to do this
- If it's being done manually, we could borrow the algorithm

**Comment by mcchong** [comment]
Sort of nontrivial, need to display arbitrary graph.
- Move components by left-click dragging them
- Move all components by dragging the background
- Components have context menus
- Hide component by selecting 'hide' in the context menu
- Show/reposition a component by right-click in background and selecting component by name
- Context menu for component also allows us to select a graph (type of data) to show for the component

**Comment by mcchong** [comment]
Restoring a simulation file from a layout is done here:
https://github.com/ctn-waterloo/nengo_1.4/blob/master/simulator-ui/python/timeview/view.py?source=cc
see restore()

**Comment by gmdavis** [comment]
I'm going to tackle the graph drawing in the following stages:
- [x] Draw simple nodes using Matplotlib
- [ ] Draw static graph imported from a *.layout file
- [ ] Add support for creating a layout (from graph without layout file)

**Comment by gmdavis** [comment]
- Lack of arrow drawing: https://networkx.lanl.gov/trac/ticket/423
- Discussion about this: https://groups.google.com/forum/#!msg/networkx-discuss/XIJerAXvyFM/A6rsGJkZmfAJ
