### ISSUE TITLE
Unit testing framework

### ISSUE THREAD

**Issue by amtinits** [chairmanmeow50/Brainspawn#20]
- Look into UnitTest2

**Comment by gmdavis** [comment]
This page provides a decent list of unit test frameworks: http://wiki.python.org/moin/PythonTestingToolsTaxonomy

**Comment by gmdavis** [comment]
The testing tool pytest has been added to the vagrant manifest file. Instructions with how to write tests will be written up into a wiki page shortly. Run all tests with "> py.test".
