### ISSUE TITLE
Save to vector PDF from UI

### ISSUE THREAD

**Issue by amtinits** [chairmanmeow50/Brainspawn#22]
- This is for the entire UI and individual visualizations

**Comment by mcchong** [comment]
If we save to the same dir with the same name, do we want to overwrite the old file without a dialog or something?

Not an issue for the demo.  Printing looks good though.

**Comment by amtinits** [comment]
Yep I agree I'll definitely add a warning for that.

**Comment by amtinits** [comment]
Saving the entire UI to a vector PDF will require GTK3 for full Cairo support.  This is a pretty big change so I'm bumping it to the next milestone.  It looks like GTK3 is pretty easy to install but the matplotlib backend for it is not available in the current Ubuntu package.  This will require building the latest matplotlib from source.
