### ISSUE TITLE
Automatically generated documentation

### ISSUE THREAD

**Issue by amtinits** [chairmanmeow50/Brainspawn#28]
- [x] Is there a way to have doc strings picked up and presented nicely?
- [ ] Would these doc strings be able to highlight parameters?
- [ ] Are there some tools to generate these doc strings (while developing)?

---
- Look into http://sphinx-doc.org/

**Comment by gmdavis** [comment]
Sphinx looks awesome.
- It will automatically pick up doc strings, and optionally link to source code
- It uses 'make' to create a large number of output formats from the documentation files 
  - HTML, tex, PDF via. laytex, XML, text, etc.
- Lots of examples:
  - Many python API doc sites use this and give an option to see their formatting code
  - E.g. http://docs.python.org/2/library/unittest.html#unittest.TestCase

**Comment by gmdavis** [comment]
Here's some decent instructions: http://pythonhosted.org/an_example_pypi_project/sphinx.html#documenting-your-project-using-sphinx

**Comment by gmdavis** [comment]
I'm closing this for now. The documentation infrastructure is up and a wikipage for its use will follow.
