### ISSUE TITLE
Simulator controls (basic)

### ISSUE THREAD

**Issue by mcchong** [chairmanmeow50/Brainspawn#37]
Controls for the simulator
- Play/Pause button
- Reset button, clears all data, resets to beginning
- Slider that shows the current time in the simulation, slide back and forth to observe data from different times in the simulation
- Jump to front, jump to end buttons
- Earliest time/Latest time labels
- Slider remains at right end of value when 'simulating' (generating more data)
- Slider progresses towards right during 'playback' of data

**Comment by chairmanmeow50** [comment]
earliest time/latest time labels seem unnecessary atm, since it will always show 0, and max tick time
during playback it will show the max tick time anyways
