### ISSUE TITLE
Value graph

### ISSUE THREAD

**Issue by mcchong** [chairmanmeow50/Brainspawn#38]
Simple XY Graph that shows 'value' being represented
- Right click a component that represents a value (input, ensemble), select 'value', create a graph to show value
- Move the graph by  left-click dragging it
- Resize it by dragging near the corners or using the mouse scroll wheel
- Press play button to show data that accurately represents its value.

We should be able to test this using an example similar to some very simple examples in the Nengo 1.4 'demo' scripts, which can be found here: http://nengo.ca/download.

**Comment by chairmanmeow50** [comment]
add multiple lines
