### ISSUE TITLE
Port spike raster

### ISSUE THREAD

**Issue by mcchong** [chairmanmeow50/Brainspawn#40]
Spike raster shows the individual spikes coming from the neurons.  For ensembles with large numbers of neurons (how many?), only a subset of them are shown (what subset?).
- Using the context menu, you can adjust the proportion of spikes shown (from 5-50%, see visualizer for example)
- Running a simulation, and varying input will affect neuron firing patterns
- Find some way to test components

**Comment by amtinits** [comment]
Looks like the Nengo guys recently did this here: https://github.com/ctn-waterloo/nengo/blob/master/nengo/matplotlib.py
